
language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

jdk:
  - oraclejdk8

notifications:
  email: false

script: ./gradlew assemble check

after_success:
    - bash <(curl -s https://codecov.io/bash)
